name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-typecheck-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-portal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ai-portal/package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('ai-portal/package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Prisma generate and migrate
        run: |
          npx prisma generate
          npx prisma migrate dev --name ci --skip-generate

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          E2E_BYPASS_AUTH: '1'
        run: npx playwright test --reporter=line

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ai-portal/playwright-report/
          if-no-files-found: ignore
